### ISSUE TITLE
Strange path to fontawesome-webfont.ttf causes file not found exception

### ISSUE THREAD

**Issue by mbooh** [Geta/geta-optimizely-contenttypeicons#11]
We find some of these exceptions in the Windows event log.

`EventId: 2
SpanId: 63e56c34970fc96b
TraceId: 7636632c140d7a26b1091215e1a16614
ParentId: 0000000000000000
RequestId: 80000d4f-0005-f400-b63f-84710c7967bb
RequestPath: /Geta_Optimizely_ContentTypeIcons

Connection ID "17582052968339868972", Request ID "80000d4f-0005-f400-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.InvalidOperationException: Unable to load font fa4/fonts/fontawesome-webfont.ttf from EmbeddedResource
 ---> System.IO.FileNotFoundException: The file /ClientResources/ClientResources/fa4/fonts/fontawesome-webfont.ttf does not exist.
   at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.LoadFontFamilyFromClientResources(String fileName)
   --- End of inner exception stack trace ---
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.LoadFontFamilyFromClientResources(String fileName)
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.GenerateImage(ContentTypeIconSettings settings)
   at Geta.Optimizely.ContentTypeIcons.ContentTypeIconService.LoadIconImage(ContentTypeIconSettings settings)
   at Geta.Optimizely.ContentTypeIcons.Controllers.ContentTypeIconController.Index(ContentTypeIconSettings settings)
   at lambda_method31310(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at EPiServer.Middleware.InitializeOnFirstRequestMiddleware.InvokeAsync(HttpContext httpContext)
   at EPiServer.Framework.DependencyInjection.Internal.VisitorGroupMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
`
The path is **/ClientResources/ClientResources/fa4/fonts/fontawesome-webfont.ttf** which seems strange?

Any idea what could cause this?
We are running version 2.0.2 and Optimizely 12.9.3

**Comment by mbooh** [comment]
Forget about this. Configuration was missing in Startup.
